Standalone
humanmade/aws-analytics pull request #345
Opened 2022-03-04 09:44 UTC by joehoyle

2022-03-11 00:28 UTC, rmccue requested changes

2022-03-11 00:28 UTC, rmccue commented on inc/utils/namespace.php
> +function get_elasticsearch_index_path() : string {
Needs phpdoc

2022-03-11 00:28 UTC, rmccue commented on inc/utils/namespace.php
> +	$index_path = apply_filters( 'altis.analytics.elasticsearch.index-path', 'analytics-' );
`prefix` seems like it'd be better?

2022-03-11 00:28 UTC, rmccue commented on inc/utils/namespace.php
> +	$index_path = apply_filters( 'altis.analytics.elasticsearch.index-path', 'analytics-' );
As above

2022-03-15 07:53 UTC, shadyvb approved these changes

2022-03-15 07:56 UTC, merged